### ISSUE TITLE
Inserting an URL without 'http(s)://' breaks functionality

### ISSUE THREAD

**Issue by TheGuyDanish** [bauripalash/fossurl#1] opened 2018-06-18 06:56 UTC
While testing, I noticed that putting an URL without the entire http://-preamble means the page won't forward to the shortened URL correctly.

For example:
Inputting only 'cnn.com', I got this URL: https://fossurl.palash.tk/#o1snc2 - Going to it gives a 404 as it expands to https://fossurl.palash.tk/cnn.com

Perhaps do a check in JavaScript for the presence of the 'http://' or 'https://', and if it isn't there, add it?

**Comment by bauripalash** [comment] 2018-06-18 10:13
Thank you for Letting me know the issue.

I spotted the issue and working on it.

**Comment by bauripalash** [comment] 2018-06-19 05:01
@TheGuyDanish  
i think the issue is fixed now with this commit 81f0e7eed55c7bf85b445455be2c6bf614c0b86c 
please check and close this issue if solved.

**Comment by bauripalash** [comment] 2018-06-19 11:51
Issue is solved , clear your cache before testing.

**Closed as completed by bauripalash** 2018-06-19 11:51 UTC
